// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package filestore

import (
	"io"
	"sync"
)

// Ensure, that FileStoreMock does implement FileStore.
// If this is not the case, regenerate this file with moq.
var _ FileStore = &FileStoreMock{}

// FileStoreMock is a mock implementation of FileStore.
//
//	func TestSomethingThatUsesFileStore(t *testing.T) {
//
//		// make and configure a mocked FileStore
//		mockedFileStore := &FileStoreMock{
//			DiskPathFunc: func(s string) string {
//				panic("mock out the DiskPath method")
//			},
//			SaveFunc: func(path string, data io.Reader) (*FileInfo, error) {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedFileStore in code that requires FileStore
//		// and then make assertions.
//
//	}
type FileStoreMock struct {
	// DiskPathFunc mocks the DiskPath method.
	DiskPathFunc func(s string) string

	// SaveFunc mocks the Save method.
	SaveFunc func(path string, data io.Reader) (*FileInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// DiskPath holds details about calls to the DiskPath method.
		DiskPath []struct {
			// S is the s argument value.
			S string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Path is the path argument value.
			Path string
			// Data is the data argument value.
			Data io.Reader
		}
	}
	lockDiskPath sync.RWMutex
	lockSave     sync.RWMutex
}

// DiskPath calls DiskPathFunc.
func (mock *FileStoreMock) DiskPath(s string) string {
	if mock.DiskPathFunc == nil {
		panic("FileStoreMock.DiskPathFunc: method is nil but FileStore.DiskPath was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockDiskPath.Lock()
	mock.calls.DiskPath = append(mock.calls.DiskPath, callInfo)
	mock.lockDiskPath.Unlock()
	return mock.DiskPathFunc(s)
}

// DiskPathCalls gets all the calls that were made to DiskPath.
// Check the length with:
//
//	len(mockedFileStore.DiskPathCalls())
func (mock *FileStoreMock) DiskPathCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockDiskPath.RLock()
	calls = mock.calls.DiskPath
	mock.lockDiskPath.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *FileStoreMock) Save(path string, data io.Reader) (*FileInfo, error) {
	if mock.SaveFunc == nil {
		panic("FileStoreMock.SaveFunc: method is nil but FileStore.Save was just called")
	}
	callInfo := struct {
		Path string
		Data io.Reader
	}{
		Path: path,
		Data: data,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(path, data)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedFileStore.SaveCalls())
func (mock *FileStoreMock) SaveCalls() []struct {
	Path string
	Data io.Reader
} {
	var calls []struct {
		Path string
		Data io.Reader
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
