// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pglib

import (
	"context"
	"sync"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Ensure, that PoolMock does implement Pool.
// If this is not the case, regenerate this file with moq.
var _ Pool = &PoolMock{}

// PoolMock is a mock implementation of Pool.
//
//	func TestSomethingThatUsesPool(t *testing.T) {
//
//		// make and configure a mocked Pool
//		mockedPool := &PoolMock{
//			BeginFunc: func(ctx context.Context) (pgx.Tx, error) {
//				panic("mock out the Begin method")
//			},
//			BeginTxFunc: func(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error) {
//				panic("mock out the BeginTx method")
//			},
//			ExecFunc: func(ctx context.Context, query string, args ...any) (pgconn.CommandTag, error) {
//				panic("mock out the Exec method")
//			},
//			QueryFunc: func(ctx context.Context, query string, args ...any) (pgx.Rows, error) {
//				panic("mock out the Query method")
//			},
//			QueryRowFunc: func(ctx context.Context, query string, args ...any) pgx.Row {
//				panic("mock out the QueryRow method")
//			},
//		}
//
//		// use mockedPool in code that requires Pool
//		// and then make assertions.
//
//	}
type PoolMock struct {
	// BeginFunc mocks the Begin method.
	BeginFunc func(ctx context.Context) (pgx.Tx, error)

	// BeginTxFunc mocks the BeginTx method.
	BeginTxFunc func(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error)

	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, query string, args ...any) (pgconn.CommandTag, error)

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, query string, args ...any) (pgx.Rows, error)

	// QueryRowFunc mocks the QueryRow method.
	QueryRowFunc func(ctx context.Context, query string, args ...any) pgx.Row

	// calls tracks calls to the methods.
	calls struct {
		// Begin holds details about calls to the Begin method.
		Begin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// BeginTx holds details about calls to the BeginTx method.
		BeginTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts pgx.TxOptions
		}
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
		// QueryRow holds details about calls to the QueryRow method.
		QueryRow []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Args is the args argument value.
			Args []any
		}
	}
	lockBegin    sync.RWMutex
	lockBeginTx  sync.RWMutex
	lockExec     sync.RWMutex
	lockQuery    sync.RWMutex
	lockQueryRow sync.RWMutex
}

// Begin calls BeginFunc.
func (mock *PoolMock) Begin(ctx context.Context) (pgx.Tx, error) {
	if mock.BeginFunc == nil {
		panic("PoolMock.BeginFunc: method is nil but Pool.Begin was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBegin.Lock()
	mock.calls.Begin = append(mock.calls.Begin, callInfo)
	mock.lockBegin.Unlock()
	return mock.BeginFunc(ctx)
}

// BeginCalls gets all the calls that were made to Begin.
// Check the length with:
//
//	len(mockedPool.BeginCalls())
func (mock *PoolMock) BeginCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBegin.RLock()
	calls = mock.calls.Begin
	mock.lockBegin.RUnlock()
	return calls
}

// BeginTx calls BeginTxFunc.
func (mock *PoolMock) BeginTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error) {
	if mock.BeginTxFunc == nil {
		panic("PoolMock.BeginTxFunc: method is nil but Pool.BeginTx was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts pgx.TxOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockBeginTx.Lock()
	mock.calls.BeginTx = append(mock.calls.BeginTx, callInfo)
	mock.lockBeginTx.Unlock()
	return mock.BeginTxFunc(ctx, opts)
}

// BeginTxCalls gets all the calls that were made to BeginTx.
// Check the length with:
//
//	len(mockedPool.BeginTxCalls())
func (mock *PoolMock) BeginTxCalls() []struct {
	Ctx  context.Context
	Opts pgx.TxOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts pgx.TxOptions
	}
	mock.lockBeginTx.RLock()
	calls = mock.calls.BeginTx
	mock.lockBeginTx.RUnlock()
	return calls
}

// Exec calls ExecFunc.
func (mock *PoolMock) Exec(ctx context.Context, query string, args ...any) (pgconn.CommandTag, error) {
	if mock.ExecFunc == nil {
		panic("PoolMock.ExecFunc: method is nil but Pool.Exec was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, query, args...)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedPool.ExecCalls())
func (mock *PoolMock) ExecCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *PoolMock) Query(ctx context.Context, query string, args ...any) (pgx.Rows, error) {
	if mock.QueryFunc == nil {
		panic("PoolMock.QueryFunc: method is nil but Pool.Query was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, query, args...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedPool.QueryCalls())
func (mock *PoolMock) QueryCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// QueryRow calls QueryRowFunc.
func (mock *PoolMock) QueryRow(ctx context.Context, query string, args ...any) pgx.Row {
	if mock.QueryRowFunc == nil {
		panic("PoolMock.QueryRowFunc: method is nil but Pool.QueryRow was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Args  []any
	}{
		Ctx:   ctx,
		Query: query,
		Args:  args,
	}
	mock.lockQueryRow.Lock()
	mock.calls.QueryRow = append(mock.calls.QueryRow, callInfo)
	mock.lockQueryRow.Unlock()
	return mock.QueryRowFunc(ctx, query, args...)
}

// QueryRowCalls gets all the calls that were made to QueryRow.
// Check the length with:
//
//	len(mockedPool.QueryRowCalls())
func (mock *PoolMock) QueryRowCalls() []struct {
	Ctx   context.Context
	Query string
	Args  []any
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Args  []any
	}
	mock.lockQueryRow.RLock()
	calls = mock.calls.QueryRow
	mock.lockQueryRow.RUnlock()
	return calls
}
