// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pglib

import (
	"sync"
)

// Ensure, that RowMock does implement Row.
// If this is not the case, regenerate this file with moq.
var _ Row = &RowMock{}

// RowMock is a mock implementation of Row.
//
//	func TestSomethingThatUsesRow(t *testing.T) {
//
//		// make and configure a mocked Row
//		mockedRow := &RowMock{
//			ScanFunc: func(dest ...any) error {
//				panic("mock out the Scan method")
//			},
//		}
//
//		// use mockedRow in code that requires Row
//		// and then make assertions.
//
//	}
type RowMock struct {
	// ScanFunc mocks the Scan method.
	ScanFunc func(dest ...any) error

	// calls tracks calls to the methods.
	calls struct {
		// Scan holds details about calls to the Scan method.
		Scan []struct {
			// Dest is the dest argument value.
			Dest []any
		}
	}
	lockScan sync.RWMutex
}

// Scan calls ScanFunc.
func (mock *RowMock) Scan(dest ...any) error {
	if mock.ScanFunc == nil {
		panic("RowMock.ScanFunc: method is nil but Row.Scan was just called")
	}
	callInfo := struct {
		Dest []any
	}{
		Dest: dest,
	}
	mock.lockScan.Lock()
	mock.calls.Scan = append(mock.calls.Scan, callInfo)
	mock.lockScan.Unlock()
	return mock.ScanFunc(dest...)
}

// ScanCalls gets all the calls that were made to Scan.
// Check the length with:
//
//	len(mockedRow.ScanCalls())
func (mock *RowMock) ScanCalls() []struct {
	Dest []any
} {
	var calls []struct {
		Dest []any
	}
	mock.lockScan.RLock()
	calls = mock.calls.Scan
	mock.lockScan.RUnlock()
	return calls
}
