// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pglib

import (
	"sync"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Ensure, that RowsMock does implement Rows.
// If this is not the case, regenerate this file with moq.
var _ Rows = &RowsMock{}

// RowsMock is a mock implementation of Rows.
//
//	func TestSomethingThatUsesRows(t *testing.T) {
//
//		// make and configure a mocked Rows
//		mockedRows := &RowsMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			CommandTagFunc: func() pgconn.CommandTag {
//				panic("mock out the CommandTag method")
//			},
//			ConnFunc: func() *pgx.Conn {
//				panic("mock out the Conn method")
//			},
//			ErrFunc: func() error {
//				panic("mock out the Err method")
//			},
//			FieldDescriptionsFunc: func() []pgconn.FieldDescription {
//				panic("mock out the FieldDescriptions method")
//			},
//			NextFunc: func() bool {
//				panic("mock out the Next method")
//			},
//			RawValuesFunc: func() [][]byte {
//				panic("mock out the RawValues method")
//			},
//			ScanFunc: func(dest ...any) error {
//				panic("mock out the Scan method")
//			},
//			ValuesFunc: func() ([]any, error) {
//				panic("mock out the Values method")
//			},
//		}
//
//		// use mockedRows in code that requires Rows
//		// and then make assertions.
//
//	}
type RowsMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// CommandTagFunc mocks the CommandTag method.
	CommandTagFunc func() pgconn.CommandTag

	// ConnFunc mocks the Conn method.
	ConnFunc func() *pgx.Conn

	// ErrFunc mocks the Err method.
	ErrFunc func() error

	// FieldDescriptionsFunc mocks the FieldDescriptions method.
	FieldDescriptionsFunc func() []pgconn.FieldDescription

	// NextFunc mocks the Next method.
	NextFunc func() bool

	// RawValuesFunc mocks the RawValues method.
	RawValuesFunc func() [][]byte

	// ScanFunc mocks the Scan method.
	ScanFunc func(dest ...any) error

	// ValuesFunc mocks the Values method.
	ValuesFunc func() ([]any, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CommandTag holds details about calls to the CommandTag method.
		CommandTag []struct {
		}
		// Conn holds details about calls to the Conn method.
		Conn []struct {
		}
		// Err holds details about calls to the Err method.
		Err []struct {
		}
		// FieldDescriptions holds details about calls to the FieldDescriptions method.
		FieldDescriptions []struct {
		}
		// Next holds details about calls to the Next method.
		Next []struct {
		}
		// RawValues holds details about calls to the RawValues method.
		RawValues []struct {
		}
		// Scan holds details about calls to the Scan method.
		Scan []struct {
			// Dest is the dest argument value.
			Dest []any
		}
		// Values holds details about calls to the Values method.
		Values []struct {
		}
	}
	lockClose             sync.RWMutex
	lockCommandTag        sync.RWMutex
	lockConn              sync.RWMutex
	lockErr               sync.RWMutex
	lockFieldDescriptions sync.RWMutex
	lockNext              sync.RWMutex
	lockRawValues         sync.RWMutex
	lockScan              sync.RWMutex
	lockValues            sync.RWMutex
}

// Close calls CloseFunc.
func (mock *RowsMock) Close() {
	if mock.CloseFunc == nil {
		panic("RowsMock.CloseFunc: method is nil but Rows.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedRows.CloseCalls())
func (mock *RowsMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CommandTag calls CommandTagFunc.
func (mock *RowsMock) CommandTag() pgconn.CommandTag {
	if mock.CommandTagFunc == nil {
		panic("RowsMock.CommandTagFunc: method is nil but Rows.CommandTag was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCommandTag.Lock()
	mock.calls.CommandTag = append(mock.calls.CommandTag, callInfo)
	mock.lockCommandTag.Unlock()
	return mock.CommandTagFunc()
}

// CommandTagCalls gets all the calls that were made to CommandTag.
// Check the length with:
//
//	len(mockedRows.CommandTagCalls())
func (mock *RowsMock) CommandTagCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommandTag.RLock()
	calls = mock.calls.CommandTag
	mock.lockCommandTag.RUnlock()
	return calls
}

// Conn calls ConnFunc.
func (mock *RowsMock) Conn() *pgx.Conn {
	if mock.ConnFunc == nil {
		panic("RowsMock.ConnFunc: method is nil but Rows.Conn was just called")
	}
	callInfo := struct {
	}{}
	mock.lockConn.Lock()
	mock.calls.Conn = append(mock.calls.Conn, callInfo)
	mock.lockConn.Unlock()
	return mock.ConnFunc()
}

// ConnCalls gets all the calls that were made to Conn.
// Check the length with:
//
//	len(mockedRows.ConnCalls())
func (mock *RowsMock) ConnCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConn.RLock()
	calls = mock.calls.Conn
	mock.lockConn.RUnlock()
	return calls
}

// Err calls ErrFunc.
func (mock *RowsMock) Err() error {
	if mock.ErrFunc == nil {
		panic("RowsMock.ErrFunc: method is nil but Rows.Err was just called")
	}
	callInfo := struct {
	}{}
	mock.lockErr.Lock()
	mock.calls.Err = append(mock.calls.Err, callInfo)
	mock.lockErr.Unlock()
	return mock.ErrFunc()
}

// ErrCalls gets all the calls that were made to Err.
// Check the length with:
//
//	len(mockedRows.ErrCalls())
func (mock *RowsMock) ErrCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockErr.RLock()
	calls = mock.calls.Err
	mock.lockErr.RUnlock()
	return calls
}

// FieldDescriptions calls FieldDescriptionsFunc.
func (mock *RowsMock) FieldDescriptions() []pgconn.FieldDescription {
	if mock.FieldDescriptionsFunc == nil {
		panic("RowsMock.FieldDescriptionsFunc: method is nil but Rows.FieldDescriptions was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFieldDescriptions.Lock()
	mock.calls.FieldDescriptions = append(mock.calls.FieldDescriptions, callInfo)
	mock.lockFieldDescriptions.Unlock()
	return mock.FieldDescriptionsFunc()
}

// FieldDescriptionsCalls gets all the calls that were made to FieldDescriptions.
// Check the length with:
//
//	len(mockedRows.FieldDescriptionsCalls())
func (mock *RowsMock) FieldDescriptionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFieldDescriptions.RLock()
	calls = mock.calls.FieldDescriptions
	mock.lockFieldDescriptions.RUnlock()
	return calls
}

// Next calls NextFunc.
func (mock *RowsMock) Next() bool {
	if mock.NextFunc == nil {
		panic("RowsMock.NextFunc: method is nil but Rows.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedRows.NextCalls())
func (mock *RowsMock) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// RawValues calls RawValuesFunc.
func (mock *RowsMock) RawValues() [][]byte {
	if mock.RawValuesFunc == nil {
		panic("RowsMock.RawValuesFunc: method is nil but Rows.RawValues was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRawValues.Lock()
	mock.calls.RawValues = append(mock.calls.RawValues, callInfo)
	mock.lockRawValues.Unlock()
	return mock.RawValuesFunc()
}

// RawValuesCalls gets all the calls that were made to RawValues.
// Check the length with:
//
//	len(mockedRows.RawValuesCalls())
func (mock *RowsMock) RawValuesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRawValues.RLock()
	calls = mock.calls.RawValues
	mock.lockRawValues.RUnlock()
	return calls
}

// Scan calls ScanFunc.
func (mock *RowsMock) Scan(dest ...any) error {
	if mock.ScanFunc == nil {
		panic("RowsMock.ScanFunc: method is nil but Rows.Scan was just called")
	}
	callInfo := struct {
		Dest []any
	}{
		Dest: dest,
	}
	mock.lockScan.Lock()
	mock.calls.Scan = append(mock.calls.Scan, callInfo)
	mock.lockScan.Unlock()
	return mock.ScanFunc(dest...)
}

// ScanCalls gets all the calls that were made to Scan.
// Check the length with:
//
//	len(mockedRows.ScanCalls())
func (mock *RowsMock) ScanCalls() []struct {
	Dest []any
} {
	var calls []struct {
		Dest []any
	}
	mock.lockScan.RLock()
	calls = mock.calls.Scan
	mock.lockScan.RUnlock()
	return calls
}

// Values calls ValuesFunc.
func (mock *RowsMock) Values() ([]any, error) {
	if mock.ValuesFunc == nil {
		panic("RowsMock.ValuesFunc: method is nil but Rows.Values was just called")
	}
	callInfo := struct {
	}{}
	mock.lockValues.Lock()
	mock.calls.Values = append(mock.calls.Values, callInfo)
	mock.lockValues.Unlock()
	return mock.ValuesFunc()
}

// ValuesCalls gets all the calls that were made to Values.
// Check the length with:
//
//	len(mockedRows.ValuesCalls())
func (mock *RowsMock) ValuesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockValues.RLock()
	calls = mock.calls.Values
	mock.lockValues.RUnlock()
	return calls
}
