// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pglib

import (
	"context"
	"sync"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Ensure, that TxMock does implement Tx.
// If this is not the case, regenerate this file with moq.
var _ Tx = &TxMock{}

// TxMock is a mock implementation of Tx.
//
//	func TestSomethingThatUsesTx(t *testing.T) {
//
//		// make and configure a mocked Tx
//		mockedTx := &TxMock{
//			BeginFunc: func(ctx context.Context) (pgx.Tx, error) {
//				panic("mock out the Begin method")
//			},
//			CommitFunc: func(ctx context.Context) error {
//				panic("mock out the Commit method")
//			},
//			ConnFunc: func() *pgx.Conn {
//				panic("mock out the Conn method")
//			},
//			CopyFromFunc: func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
//				panic("mock out the CopyFrom method")
//			},
//			ExecFunc: func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
//				panic("mock out the Exec method")
//			},
//			LargeObjectsFunc: func() pgx.LargeObjects {
//				panic("mock out the LargeObjects method")
//			},
//			PrepareFunc: func(ctx context.Context, name string, sql string) (*pgconn.StatementDescription, error) {
//				panic("mock out the Prepare method")
//			},
//			QueryFunc: func(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
//				panic("mock out the Query method")
//			},
//			QueryRowFunc: func(ctx context.Context, sql string, args ...any) pgx.Row {
//				panic("mock out the QueryRow method")
//			},
//			RollbackFunc: func(ctx context.Context) error {
//				panic("mock out the Rollback method")
//			},
//			SendBatchFunc: func(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
//				panic("mock out the SendBatch method")
//			},
//		}
//
//		// use mockedTx in code that requires Tx
//		// and then make assertions.
//
//	}
type TxMock struct {
	// BeginFunc mocks the Begin method.
	BeginFunc func(ctx context.Context) (pgx.Tx, error)

	// CommitFunc mocks the Commit method.
	CommitFunc func(ctx context.Context) error

	// ConnFunc mocks the Conn method.
	ConnFunc func() *pgx.Conn

	// CopyFromFunc mocks the CopyFrom method.
	CopyFromFunc func(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)

	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)

	// LargeObjectsFunc mocks the LargeObjects method.
	LargeObjectsFunc func() pgx.LargeObjects

	// PrepareFunc mocks the Prepare method.
	PrepareFunc func(ctx context.Context, name string, sql string) (*pgconn.StatementDescription, error)

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)

	// QueryRowFunc mocks the QueryRow method.
	QueryRowFunc func(ctx context.Context, sql string, args ...any) pgx.Row

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func(ctx context.Context) error

	// SendBatchFunc mocks the SendBatch method.
	SendBatchFunc func(ctx context.Context, b *pgx.Batch) pgx.BatchResults

	// calls tracks calls to the methods.
	calls struct {
		// Begin holds details about calls to the Begin method.
		Begin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Conn holds details about calls to the Conn method.
		Conn []struct {
		}
		// CopyFrom holds details about calls to the CopyFrom method.
		CopyFrom []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TableName is the tableName argument value.
			TableName pgx.Identifier
			// ColumnNames is the columnNames argument value.
			ColumnNames []string
			// RowSrc is the rowSrc argument value.
			RowSrc pgx.CopyFromSource
		}
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Arguments is the arguments argument value.
			Arguments []any
		}
		// LargeObjects holds details about calls to the LargeObjects method.
		LargeObjects []struct {
		}
		// Prepare holds details about calls to the Prepare method.
		Prepare []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// SQL is the sql argument value.
			SQL string
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []any
		}
		// QueryRow holds details about calls to the QueryRow method.
		QueryRow []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []any
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SendBatch holds details about calls to the SendBatch method.
		SendBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// B is the b argument value.
			B *pgx.Batch
		}
	}
	lockBegin        sync.RWMutex
	lockCommit       sync.RWMutex
	lockConn         sync.RWMutex
	lockCopyFrom     sync.RWMutex
	lockExec         sync.RWMutex
	lockLargeObjects sync.RWMutex
	lockPrepare      sync.RWMutex
	lockQuery        sync.RWMutex
	lockQueryRow     sync.RWMutex
	lockRollback     sync.RWMutex
	lockSendBatch    sync.RWMutex
}

// Begin calls BeginFunc.
func (mock *TxMock) Begin(ctx context.Context) (pgx.Tx, error) {
	if mock.BeginFunc == nil {
		panic("TxMock.BeginFunc: method is nil but Tx.Begin was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBegin.Lock()
	mock.calls.Begin = append(mock.calls.Begin, callInfo)
	mock.lockBegin.Unlock()
	return mock.BeginFunc(ctx)
}

// BeginCalls gets all the calls that were made to Begin.
// Check the length with:
//
//	len(mockedTx.BeginCalls())
func (mock *TxMock) BeginCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBegin.RLock()
	calls = mock.calls.Begin
	mock.lockBegin.RUnlock()
	return calls
}

// Commit calls CommitFunc.
func (mock *TxMock) Commit(ctx context.Context) error {
	if mock.CommitFunc == nil {
		panic("TxMock.CommitFunc: method is nil but Tx.Commit was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(ctx)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTx.CommitCalls())
func (mock *TxMock) CommitCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Conn calls ConnFunc.
func (mock *TxMock) Conn() *pgx.Conn {
	if mock.ConnFunc == nil {
		panic("TxMock.ConnFunc: method is nil but Tx.Conn was just called")
	}
	callInfo := struct {
	}{}
	mock.lockConn.Lock()
	mock.calls.Conn = append(mock.calls.Conn, callInfo)
	mock.lockConn.Unlock()
	return mock.ConnFunc()
}

// ConnCalls gets all the calls that were made to Conn.
// Check the length with:
//
//	len(mockedTx.ConnCalls())
func (mock *TxMock) ConnCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockConn.RLock()
	calls = mock.calls.Conn
	mock.lockConn.RUnlock()
	return calls
}

// CopyFrom calls CopyFromFunc.
func (mock *TxMock) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	if mock.CopyFromFunc == nil {
		panic("TxMock.CopyFromFunc: method is nil but Tx.CopyFrom was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		TableName   pgx.Identifier
		ColumnNames []string
		RowSrc      pgx.CopyFromSource
	}{
		Ctx:         ctx,
		TableName:   tableName,
		ColumnNames: columnNames,
		RowSrc:      rowSrc,
	}
	mock.lockCopyFrom.Lock()
	mock.calls.CopyFrom = append(mock.calls.CopyFrom, callInfo)
	mock.lockCopyFrom.Unlock()
	return mock.CopyFromFunc(ctx, tableName, columnNames, rowSrc)
}

// CopyFromCalls gets all the calls that were made to CopyFrom.
// Check the length with:
//
//	len(mockedTx.CopyFromCalls())
func (mock *TxMock) CopyFromCalls() []struct {
	Ctx         context.Context
	TableName   pgx.Identifier
	ColumnNames []string
	RowSrc      pgx.CopyFromSource
} {
	var calls []struct {
		Ctx         context.Context
		TableName   pgx.Identifier
		ColumnNames []string
		RowSrc      pgx.CopyFromSource
	}
	mock.lockCopyFrom.RLock()
	calls = mock.calls.CopyFrom
	mock.lockCopyFrom.RUnlock()
	return calls
}

// Exec calls ExecFunc.
func (mock *TxMock) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	if mock.ExecFunc == nil {
		panic("TxMock.ExecFunc: method is nil but Tx.Exec was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		SQL       string
		Arguments []any
	}{
		Ctx:       ctx,
		SQL:       sql,
		Arguments: arguments,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, sql, arguments...)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedTx.ExecCalls())
func (mock *TxMock) ExecCalls() []struct {
	Ctx       context.Context
	SQL       string
	Arguments []any
} {
	var calls []struct {
		Ctx       context.Context
		SQL       string
		Arguments []any
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}

// LargeObjects calls LargeObjectsFunc.
func (mock *TxMock) LargeObjects() pgx.LargeObjects {
	if mock.LargeObjectsFunc == nil {
		panic("TxMock.LargeObjectsFunc: method is nil but Tx.LargeObjects was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLargeObjects.Lock()
	mock.calls.LargeObjects = append(mock.calls.LargeObjects, callInfo)
	mock.lockLargeObjects.Unlock()
	return mock.LargeObjectsFunc()
}

// LargeObjectsCalls gets all the calls that were made to LargeObjects.
// Check the length with:
//
//	len(mockedTx.LargeObjectsCalls())
func (mock *TxMock) LargeObjectsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLargeObjects.RLock()
	calls = mock.calls.LargeObjects
	mock.lockLargeObjects.RUnlock()
	return calls
}

// Prepare calls PrepareFunc.
func (mock *TxMock) Prepare(ctx context.Context, name string, sql string) (*pgconn.StatementDescription, error) {
	if mock.PrepareFunc == nil {
		panic("TxMock.PrepareFunc: method is nil but Tx.Prepare was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		SQL  string
	}{
		Ctx:  ctx,
		Name: name,
		SQL:  sql,
	}
	mock.lockPrepare.Lock()
	mock.calls.Prepare = append(mock.calls.Prepare, callInfo)
	mock.lockPrepare.Unlock()
	return mock.PrepareFunc(ctx, name, sql)
}

// PrepareCalls gets all the calls that were made to Prepare.
// Check the length with:
//
//	len(mockedTx.PrepareCalls())
func (mock *TxMock) PrepareCalls() []struct {
	Ctx  context.Context
	Name string
	SQL  string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		SQL  string
	}
	mock.lockPrepare.RLock()
	calls = mock.calls.Prepare
	mock.lockPrepare.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *TxMock) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	if mock.QueryFunc == nil {
		panic("TxMock.QueryFunc: method is nil but Tx.Query was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, sql, args...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedTx.QueryCalls())
func (mock *TxMock) QueryCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// QueryRow calls QueryRowFunc.
func (mock *TxMock) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	if mock.QueryRowFunc == nil {
		panic("TxMock.QueryRowFunc: method is nil but Tx.QueryRow was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockQueryRow.Lock()
	mock.calls.QueryRow = append(mock.calls.QueryRow, callInfo)
	mock.lockQueryRow.Unlock()
	return mock.QueryRowFunc(ctx, sql, args...)
}

// QueryRowCalls gets all the calls that were made to QueryRow.
// Check the length with:
//
//	len(mockedTx.QueryRowCalls())
func (mock *TxMock) QueryRowCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}
	mock.lockQueryRow.RLock()
	calls = mock.calls.QueryRow
	mock.lockQueryRow.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *TxMock) Rollback(ctx context.Context) error {
	if mock.RollbackFunc == nil {
		panic("TxMock.RollbackFunc: method is nil but Tx.Rollback was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	return mock.RollbackFunc(ctx)
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTx.RollbackCalls())
func (mock *TxMock) RollbackCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}

// SendBatch calls SendBatchFunc.
func (mock *TxMock) SendBatch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	if mock.SendBatchFunc == nil {
		panic("TxMock.SendBatchFunc: method is nil but Tx.SendBatch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		B   *pgx.Batch
	}{
		Ctx: ctx,
		B:   b,
	}
	mock.lockSendBatch.Lock()
	mock.calls.SendBatch = append(mock.calls.SendBatch, callInfo)
	mock.lockSendBatch.Unlock()
	return mock.SendBatchFunc(ctx, b)
}

// SendBatchCalls gets all the calls that were made to SendBatch.
// Check the length with:
//
//	len(mockedTx.SendBatchCalls())
func (mock *TxMock) SendBatchCalls() []struct {
	Ctx context.Context
	B   *pgx.Batch
} {
	var calls []struct {
		Ctx context.Context
		B   *pgx.Batch
	}
	mock.lockSendBatch.RLock()
	calls = mock.calls.SendBatch
	mock.lockSendBatch.RUnlock()
	return calls
}
