// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"sync"

	"github.com/google/uuid"
)

// Ensure, that PgxStoreMock does implement PgxStore.
// If this is not the case, regenerate this file with moq.
var _ PgxStore = &PgxStoreMock{}

// PgxStoreMock is a mock implementation of PgxStore.
//
//	func TestSomethingThatUsesPgxStore(t *testing.T) {
//
//		// make and configure a mocked PgxStore
//		mockedPgxStore := &PgxStoreMock{
//			CreateFunc: func(ctx context.Context, email string, username string, passwordHash string, salt string, iterations int64) (*User, error) {
//				panic("mock out the Create method")
//			},
//			GetByEmailFunc: func(ctx context.Context, email string) (*User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*User, error) {
//				panic("mock out the GetByID method")
//			},
//		}
//
//		// use mockedPgxStore in code that requires PgxStore
//		// and then make assertions.
//
//	}
type PgxStoreMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, email string, username string, passwordHash string, salt string, iterations int64) (*User, error)

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Username is the username argument value.
			Username string
			// PasswordHash is the passwordHash argument value.
			PasswordHash string
			// Salt is the salt argument value.
			Salt string
			// Iterations is the iterations argument value.
			Iterations int64
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockCreate     sync.RWMutex
	lockGetByEmail sync.RWMutex
	lockGetByID    sync.RWMutex
}

// Create calls CreateFunc.
func (mock *PgxStoreMock) Create(ctx context.Context, email string, username string, passwordHash string, salt string, iterations int64) (*User, error) {
	if mock.CreateFunc == nil {
		panic("PgxStoreMock.CreateFunc: method is nil but PgxStore.Create was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Email        string
		Username     string
		PasswordHash string
		Salt         string
		Iterations   int64
	}{
		Ctx:          ctx,
		Email:        email,
		Username:     username,
		PasswordHash: passwordHash,
		Salt:         salt,
		Iterations:   iterations,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, email, username, passwordHash, salt, iterations)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedPgxStore.CreateCalls())
func (mock *PgxStoreMock) CreateCalls() []struct {
	Ctx          context.Context
	Email        string
	Username     string
	PasswordHash string
	Salt         string
	Iterations   int64
} {
	var calls []struct {
		Ctx          context.Context
		Email        string
		Username     string
		PasswordHash string
		Salt         string
		Iterations   int64
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *PgxStoreMock) GetByEmail(ctx context.Context, email string) (*User, error) {
	if mock.GetByEmailFunc == nil {
		panic("PgxStoreMock.GetByEmailFunc: method is nil but PgxStore.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedPgxStore.GetByEmailCalls())
func (mock *PgxStoreMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *PgxStoreMock) GetByID(ctx context.Context, id uuid.UUID) (*User, error) {
	if mock.GetByIDFunc == nil {
		panic("PgxStoreMock.GetByIDFunc: method is nil but PgxStore.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedPgxStore.GetByIDCalls())
func (mock *PgxStoreMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}
