// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"sync"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked Service
//		mockedService := &ServiceMock{
//			GenerateTokenFunc: func(user *User) (string, error) {
//				panic("mock out the GenerateToken method")
//			},
//			RegisterFunc: func(ctx context.Context, email string, username string, password string) (*User, error) {
//				panic("mock out the Register method")
//			},
//			ValidatePasswordFunc: func(ctx context.Context, email string, password string) (*User, error) {
//				panic("mock out the ValidatePassword method")
//			},
//		}
//
//		// use mockedService in code that requires Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// GenerateTokenFunc mocks the GenerateToken method.
	GenerateTokenFunc func(user *User) (string, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, email string, username string, password string) (*User, error)

	// ValidatePasswordFunc mocks the ValidatePassword method.
	ValidatePasswordFunc func(ctx context.Context, email string, password string) (*User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateToken holds details about calls to the GenerateToken method.
		GenerateToken []struct {
			// User is the user argument value.
			User *User
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Username is the username argument value.
			Username string
			// Password is the password argument value.
			Password string
		}
		// ValidatePassword holds details about calls to the ValidatePassword method.
		ValidatePassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Password is the password argument value.
			Password string
		}
	}
	lockGenerateToken    sync.RWMutex
	lockRegister         sync.RWMutex
	lockValidatePassword sync.RWMutex
}

// GenerateToken calls GenerateTokenFunc.
func (mock *ServiceMock) GenerateToken(user *User) (string, error) {
	if mock.GenerateTokenFunc == nil {
		panic("ServiceMock.GenerateTokenFunc: method is nil but Service.GenerateToken was just called")
	}
	callInfo := struct {
		User *User
	}{
		User: user,
	}
	mock.lockGenerateToken.Lock()
	mock.calls.GenerateToken = append(mock.calls.GenerateToken, callInfo)
	mock.lockGenerateToken.Unlock()
	return mock.GenerateTokenFunc(user)
}

// GenerateTokenCalls gets all the calls that were made to GenerateToken.
// Check the length with:
//
//	len(mockedService.GenerateTokenCalls())
func (mock *ServiceMock) GenerateTokenCalls() []struct {
	User *User
} {
	var calls []struct {
		User *User
	}
	mock.lockGenerateToken.RLock()
	calls = mock.calls.GenerateToken
	mock.lockGenerateToken.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *ServiceMock) Register(ctx context.Context, email string, username string, password string) (*User, error) {
	if mock.RegisterFunc == nil {
		panic("ServiceMock.RegisterFunc: method is nil but Service.Register was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Email    string
		Username string
		Password string
	}{
		Ctx:      ctx,
		Email:    email,
		Username: username,
		Password: password,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, email, username, password)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedService.RegisterCalls())
func (mock *ServiceMock) RegisterCalls() []struct {
	Ctx      context.Context
	Email    string
	Username string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Email    string
		Username string
		Password string
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// ValidatePassword calls ValidatePasswordFunc.
func (mock *ServiceMock) ValidatePassword(ctx context.Context, email string, password string) (*User, error) {
	if mock.ValidatePasswordFunc == nil {
		panic("ServiceMock.ValidatePasswordFunc: method is nil but Service.ValidatePassword was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Email    string
		Password string
	}{
		Ctx:      ctx,
		Email:    email,
		Password: password,
	}
	mock.lockValidatePassword.Lock()
	mock.calls.ValidatePassword = append(mock.calls.ValidatePassword, callInfo)
	mock.lockValidatePassword.Unlock()
	return mock.ValidatePasswordFunc(ctx, email, password)
}

// ValidatePasswordCalls gets all the calls that were made to ValidatePassword.
// Check the length with:
//
//	len(mockedService.ValidatePasswordCalls())
func (mock *ServiceMock) ValidatePasswordCalls() []struct {
	Ctx      context.Context
	Email    string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Email    string
		Password string
	}
	mock.lockValidatePassword.RLock()
	calls = mock.calls.ValidatePassword
	mock.lockValidatePassword.RUnlock()
	return calls
}
