// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"context"
	"sync"

	"github.com/google/uuid"
)

// Ensure, that PgxStoreMock does implement PgxStore.
// If this is not the case, regenerate this file with moq.
var _ PgxStore = &PgxStoreMock{}

// PgxStoreMock is a mock implementation of PgxStore.
//
//	func TestSomethingThatUsesPgxStore(t *testing.T) {
//
//		// make and configure a mocked PgxStore
//		mockedPgxStore := &PgxStoreMock{
//			CreateFunc: func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID, fileName string, filePath string, contentType string) (*Document, error) {
//				panic("mock out the Create method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*Document, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]*Document, error) {
//				panic("mock out the GetByUserID method")
//			},
//			UpdateFunc: func(ctx context.Context, id uuid.UUID, req *UpdateRequest) (*Document, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedPgxStore in code that requires PgxStore
//		// and then make assertions.
//
//	}
type PgxStoreMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, fileID uuid.UUID, userID uuid.UUID, fileName string, filePath string, contentType string) (*Document, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*Document, error)

	// GetByUserIDFunc mocks the GetByUserID method.
	GetByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]*Document, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id uuid.UUID, req *UpdateRequest) (*Document, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FileID is the fileID argument value.
			FileID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
			// FileName is the fileName argument value.
			FileName string
			// FilePath is the filePath argument value.
			FilePath string
			// ContentType is the contentType argument value.
			ContentType string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByUserID holds details about calls to the GetByUserID method.
		GetByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Req is the req argument value.
			Req *UpdateRequest
		}
	}
	lockCreate      sync.RWMutex
	lockGetByID     sync.RWMutex
	lockGetByUserID sync.RWMutex
	lockUpdate      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *PgxStoreMock) Create(ctx context.Context, fileID uuid.UUID, userID uuid.UUID, fileName string, filePath string, contentType string) (*Document, error) {
	if mock.CreateFunc == nil {
		panic("PgxStoreMock.CreateFunc: method is nil but PgxStore.Create was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		FileID      uuid.UUID
		UserID      uuid.UUID
		FileName    string
		FilePath    string
		ContentType string
	}{
		Ctx:         ctx,
		FileID:      fileID,
		UserID:      userID,
		FileName:    fileName,
		FilePath:    filePath,
		ContentType: contentType,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, fileID, userID, fileName, filePath, contentType)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedPgxStore.CreateCalls())
func (mock *PgxStoreMock) CreateCalls() []struct {
	Ctx         context.Context
	FileID      uuid.UUID
	UserID      uuid.UUID
	FileName    string
	FilePath    string
	ContentType string
} {
	var calls []struct {
		Ctx         context.Context
		FileID      uuid.UUID
		UserID      uuid.UUID
		FileName    string
		FilePath    string
		ContentType string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *PgxStoreMock) GetByID(ctx context.Context, id uuid.UUID) (*Document, error) {
	if mock.GetByIDFunc == nil {
		panic("PgxStoreMock.GetByIDFunc: method is nil but PgxStore.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedPgxStore.GetByIDCalls())
func (mock *PgxStoreMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByUserID calls GetByUserIDFunc.
func (mock *PgxStoreMock) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*Document, error) {
	if mock.GetByUserIDFunc == nil {
		panic("PgxStoreMock.GetByUserIDFunc: method is nil but PgxStore.GetByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetByUserID.Lock()
	mock.calls.GetByUserID = append(mock.calls.GetByUserID, callInfo)
	mock.lockGetByUserID.Unlock()
	return mock.GetByUserIDFunc(ctx, userID)
}

// GetByUserIDCalls gets all the calls that were made to GetByUserID.
// Check the length with:
//
//	len(mockedPgxStore.GetByUserIDCalls())
func (mock *PgxStoreMock) GetByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetByUserID.RLock()
	calls = mock.calls.GetByUserID
	mock.lockGetByUserID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *PgxStoreMock) Update(ctx context.Context, id uuid.UUID, req *UpdateRequest) (*Document, error) {
	if mock.UpdateFunc == nil {
		panic("PgxStoreMock.UpdateFunc: method is nil but PgxStore.Update was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
		Req *UpdateRequest
	}{
		Ctx: ctx,
		ID:  id,
		Req: req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedPgxStore.UpdateCalls())
func (mock *PgxStoreMock) UpdateCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
	Req *UpdateRequest
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
		Req *UpdateRequest
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
