// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"context"
	"sync"

	"github.com/google/uuid"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked Service
//		mockedService := &ServiceMock{
//			GetDocumentFunc: func(ctx context.Context, userID uuid.UUID, docID uuid.UUID) (*Document, error) {
//				panic("mock out the GetDocument method")
//			},
//			ListDocumentsFunc: func(ctx context.Context, userID uuid.UUID) ([]*Document, error) {
//				panic("mock out the ListDocuments method")
//			},
//			UpdateStatusFunc: func(ctx context.Context, userID uuid.UUID, docID uuid.UUID, status string, fileSize int, checksum string) (*Document, error) {
//				panic("mock out the UpdateStatus method")
//			},
//			UploadPendingFunc: func(ctx context.Context, userID uuid.UUID, fileName string, contentType string) (*UploadPendingResponse, error) {
//				panic("mock out the UploadPending method")
//			},
//		}
//
//		// use mockedService in code that requires Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// GetDocumentFunc mocks the GetDocument method.
	GetDocumentFunc func(ctx context.Context, userID uuid.UUID, docID uuid.UUID) (*Document, error)

	// ListDocumentsFunc mocks the ListDocuments method.
	ListDocumentsFunc func(ctx context.Context, userID uuid.UUID) ([]*Document, error)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(ctx context.Context, userID uuid.UUID, docID uuid.UUID, status string, fileSize int, checksum string) (*Document, error)

	// UploadPendingFunc mocks the UploadPending method.
	UploadPendingFunc func(ctx context.Context, userID uuid.UUID, fileName string, contentType string) (*UploadPendingResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDocument holds details about calls to the GetDocument method.
		GetDocument []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// DocID is the docID argument value.
			DocID uuid.UUID
		}
		// ListDocuments holds details about calls to the ListDocuments method.
		ListDocuments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// DocID is the docID argument value.
			DocID uuid.UUID
			// Status is the status argument value.
			Status string
			// FileSize is the fileSize argument value.
			FileSize int
			// Checksum is the checksum argument value.
			Checksum string
		}
		// UploadPending holds details about calls to the UploadPending method.
		UploadPending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// FileName is the fileName argument value.
			FileName string
			// ContentType is the contentType argument value.
			ContentType string
		}
	}
	lockGetDocument   sync.RWMutex
	lockListDocuments sync.RWMutex
	lockUpdateStatus  sync.RWMutex
	lockUploadPending sync.RWMutex
}

// GetDocument calls GetDocumentFunc.
func (mock *ServiceMock) GetDocument(ctx context.Context, userID uuid.UUID, docID uuid.UUID) (*Document, error) {
	if mock.GetDocumentFunc == nil {
		panic("ServiceMock.GetDocumentFunc: method is nil but Service.GetDocument was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		DocID  uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
		DocID:  docID,
	}
	mock.lockGetDocument.Lock()
	mock.calls.GetDocument = append(mock.calls.GetDocument, callInfo)
	mock.lockGetDocument.Unlock()
	return mock.GetDocumentFunc(ctx, userID, docID)
}

// GetDocumentCalls gets all the calls that were made to GetDocument.
// Check the length with:
//
//	len(mockedService.GetDocumentCalls())
func (mock *ServiceMock) GetDocumentCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	DocID  uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		DocID  uuid.UUID
	}
	mock.lockGetDocument.RLock()
	calls = mock.calls.GetDocument
	mock.lockGetDocument.RUnlock()
	return calls
}

// ListDocuments calls ListDocumentsFunc.
func (mock *ServiceMock) ListDocuments(ctx context.Context, userID uuid.UUID) ([]*Document, error) {
	if mock.ListDocumentsFunc == nil {
		panic("ServiceMock.ListDocumentsFunc: method is nil but Service.ListDocuments was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockListDocuments.Lock()
	mock.calls.ListDocuments = append(mock.calls.ListDocuments, callInfo)
	mock.lockListDocuments.Unlock()
	return mock.ListDocumentsFunc(ctx, userID)
}

// ListDocumentsCalls gets all the calls that were made to ListDocuments.
// Check the length with:
//
//	len(mockedService.ListDocumentsCalls())
func (mock *ServiceMock) ListDocumentsCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockListDocuments.RLock()
	calls = mock.calls.ListDocuments
	mock.lockListDocuments.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *ServiceMock) UpdateStatus(ctx context.Context, userID uuid.UUID, docID uuid.UUID, status string, fileSize int, checksum string) (*Document, error) {
	if mock.UpdateStatusFunc == nil {
		panic("ServiceMock.UpdateStatusFunc: method is nil but Service.UpdateStatus was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   uuid.UUID
		DocID    uuid.UUID
		Status   string
		FileSize int
		Checksum string
	}{
		Ctx:      ctx,
		UserID:   userID,
		DocID:    docID,
		Status:   status,
		FileSize: fileSize,
		Checksum: checksum,
	}
	mock.lockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	mock.lockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(ctx, userID, docID, status, fileSize, checksum)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//
//	len(mockedService.UpdateStatusCalls())
func (mock *ServiceMock) UpdateStatusCalls() []struct {
	Ctx      context.Context
	UserID   uuid.UUID
	DocID    uuid.UUID
	Status   string
	FileSize int
	Checksum string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   uuid.UUID
		DocID    uuid.UUID
		Status   string
		FileSize int
		Checksum string
	}
	mock.lockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	mock.lockUpdateStatus.RUnlock()
	return calls
}

// UploadPending calls UploadPendingFunc.
func (mock *ServiceMock) UploadPending(ctx context.Context, userID uuid.UUID, fileName string, contentType string) (*UploadPendingResponse, error) {
	if mock.UploadPendingFunc == nil {
		panic("ServiceMock.UploadPendingFunc: method is nil but Service.UploadPending was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserID      uuid.UUID
		FileName    string
		ContentType string
	}{
		Ctx:         ctx,
		UserID:      userID,
		FileName:    fileName,
		ContentType: contentType,
	}
	mock.lockUploadPending.Lock()
	mock.calls.UploadPending = append(mock.calls.UploadPending, callInfo)
	mock.lockUploadPending.Unlock()
	return mock.UploadPendingFunc(ctx, userID, fileName, contentType)
}

// UploadPendingCalls gets all the calls that were made to UploadPending.
// Check the length with:
//
//	len(mockedService.UploadPendingCalls())
func (mock *ServiceMock) UploadPendingCalls() []struct {
	Ctx         context.Context
	UserID      uuid.UUID
	FileName    string
	ContentType string
} {
	var calls []struct {
		Ctx         context.Context
		UserID      uuid.UUID
		FileName    string
		ContentType string
	}
	mock.lockUploadPending.RLock()
	calls = mock.calls.UploadPending
	mock.lockUploadPending.RUnlock()
	return calls
}
